### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getTime' of null

### ISSUE THREAD

**Issue by NerijusD** [quantosobra/ember-semantic-ui-calendar#10]
Hi,

Has ever experienced this issue: 

![](https://content.screencast.com/users/MCB_Nerijus/folders/Jing/media/f7bf2503-0d8c-4f84-9243-05950e6c1f90/2017-11-13_1847.png)

The way I am using
```
//component-template:
...
		<div class="fields">
			<div class="four wide field"></div>

			<div class="eight wide field">
				<label>Deadline:</label>
				{{ui-calendar 
					date=myDate 
					type="date"
					onChange=(action (mut myDate)) 
					placeholder="Select date and time"}}
			</div>

			<div class="four wide field"></div>
		</div>
...
//component.js:
...
myDate: new Date(),
...
```
I tried to initialized `myDate` to `null`, `' '` and as you can see `new Date()`. Neither of those options makes difference.

**Comment by eduardoweiland** [comment]
Hi @NerijusD 

I could not reproduce this issue. It may be related to a specific version of some component. What versions of Ember, NodeJS and NPM are you using?

**Comment by NerijusD** [comment]
Hi @eduardoweiland 

I am using
```
Ember  : 2.10.2
Ember Data : 2.14.10
jQuery : 3.2.1
Ember Simple Auth : 1.1.0
NodeJs : 6.11.2
NMP : 3.10.10
```

**Comment by NerijusD** [comment]
I have update everything to latest versions. Still error happens. It seems the real issue is with `onChange=(action (mut myDate))`...

**Comment by eduardoweiland** [comment]
I just created a new Ember project, with latest Ember CLI. I've installed just semantic-ui-ember and ember-semantic-ui-calendar, and I still don't get this error.

Could you please create a new Ember project reproducing this issue and then publish to a GitHub repo?

**Comment by NerijusD** [comment]
I tried the same with completely new project and everything worked as you say. However I still had issues on my project, but then I double checked my `package.json` and found few more packages outdated:
- ember-simple-auth
- ember-simple-auth-token
- semantic-ui-ember: "2.0.0" -> "2.0.1" << probably this made the difference.

After this upgrade it started working. Thanks for your time, I really appreciate!

**Comment by eduardoweiland** [comment]
Good to know that you managed to make it work.
