### ISSUE TITLE
Adds "active" class to field but is not showing the calendar, it's remaining display:none;

### ISSUE THREAD

**Issue by joshuairl** [quantosobra/ember-semantic-ui-calendar#5]
Do I need to add more css for this?

**Comment by joshuairl** [comment]
If I add the styling manually, it doesn't close when I select the date I want.  Hmm...

**Comment by eduardoweiland** [comment]
@joshuairl Can you provide an example of the problem you are experiencing? Also, check out the [demo page](https://quantosobra.github.io/ember-semantic-ui-calendar/) to see working examples of this addon.

**Comment by joshuairl** [comment]
Magically started working .  No idea what I was doing wrong before hahaha.

We can close it.

**Comment by eduardoweiland** [comment]
Glad to know it's working!

**Comment by joshuairl** [comment]
Spoke too soon... no longer working for some reason... very weird.
When I focus the field, it does add the class as "active" but that doesn't change the display css property at all...

**Comment by joshuairl** [comment]
Oh, I'm guessing this is a semantic-ui version issue?
On the calendar css it says Semantic UI version 0.0.8 but I'm running 2.2.10?
Would that make a difference?

**Comment by joshuairl** [comment]
Nah, I guess that's just the calendar version.

**Comment by eduardoweiland** [comment]
@joshuairl Can you provide more information? Operating System, browser, and, if possible, the code you are using.

**Comment by joshuairl** [comment]
```
<div class="field">
				<label>Clip Date</label>
				{{ui-calendar type="date" date=currentlyEditing.clip_date onChange=(action (mut currentlyEditing.clip_date)) placeholder="Select date and time"}}
			</div>
```

**Comment by joshuairl** [comment]
Mac OS Sierra
Google Chrome (latest)

**Comment by eduardoweiland** [comment]
I can't think of anything that may cause this issue. But anyway, it seems more related to the [Semantic-UI-Calendar](https://github.com/mdehoog/Semantic-UI-Calendar) itself, not the Ember integration.
