### ISSUE TITLE
Unable to find jQuery Semantic UI module: calendar

### ISSUE THREAD

**Issue by georgevanvliet** [quantosobra/ember-semantic-ui-calendar#9]
I get the following error in my console:

`base.js:181 Unable to find jQuery Semantic UI module: calendar`

The component seems to work fine.

Ember 2.15.0
Ember data 2.14.11
Jquery 3.2.1

Did an `ember install ember-semantic-ui-calendar`. Already had `ember-moment` installed.

**Comment by eduardoweiland** [comment]
@georgevanvliet Can you check if bower package `semantic-ui-calendar` is installed?

**Comment by georgevanvliet** [comment]
I checked and it is installed. I found out what the problem was. In the `app/index.html` I included a version of jQuery. For some reason this collided and resulted in the above error. As soon as I removed it the above error was gone.
